# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'

    session:
        storage_factory_id: session.storage.factory.native
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax

    router:
        utf8: true
        strict_requirements: true

    csrf_protection: true
    form: ~

    validation:
        enable_attributes: true

    http_method_override: true
    assets: ~

    handle_all_throwables: true

    php_errors:
        log: true

    # Désactive l’intégration automatique des annotations
    annotations:
        enabled: false
