# config/packages/security.yaml
security:
    # enable_authenticator_manager est actif par défaut en 6.4 et déprécié en config

    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: '^/(_(profiler|wdt)|css|images|js)/'
            security: false

        main:
            pattern: '^/'
            provider: app_user_provider
            lazy: true

            form_login:
                login_path: login
                check_path: login
                default_target_path: task_list
                enable_csrf: true
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate

            logout:
                path: logout
                target: login
                invalidate_session: true

    access_control:
        - { path: '^/login',        roles: PUBLIC_ACCESS }
        - { path: '^/users/create', roles: PUBLIC_ACCESS }
        - { path: '^/users',        roles: ROLE_ADMIN }
        - { path: '^/',             roles: ROLE_USER }
