# config/routes.yaml

# Sécurité (login / logout)
login:
    path: /login
    controller: App\Controller\SecurityController::login

login_check:
    path: /login_check
    controller: App\Controller\SecurityController::loginCheck

logout:
    path: /logout
    controller: App\Controller\SecurityController::logoutCheck

# config/routes.yaml

# config/routes.yaml
task_list:
    path: /tasks
    controller: App\Controller\TaskController::listAction

task_create:
    path: /tasks/create
    controller: App\Controller\TaskController::createAction

task_edit:
    path: /tasks/{id}/edit
    controller: App\Controller\TaskController::editAction
    requirements:
        id: '\d+'

task_toggle:
    path: /tasks/{id}/toggle
    controller: App\Controller\TaskController::toggleTaskAction
    requirements:
        id: '\d+'

task_delete:
    path: /tasks/{id}/delete
    controller: App\Controller\TaskController::deleteTaskAction
    requirements:
        id: '\d+'

# Inscription
user_create:
    path: /users/create
    controller: App\Controller\UserController::createAction

user_list:
    path: /users
    controller: App\Controller\UserController::listAction
    
user_edit:
    path: /users/{id}/edit
    controller: App\Controller\UserController::editAction
    requirements:
        id: \d+


